# nuxctl (nuxctl.nuagex.io) template
# compatible with nuxctl 0.6.0+ version
template: 5c9e0f9917b3be0001d99745
name: exfo-worx-integration
sshKeys:
  - name: demo  # WARNING: make sure to use your public key instead of the demo one
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDw1jIozLL7p5Ar685vgoSqhIEKoxRn/BpvEaiZkZORZo+Ox4HHRGrW+NZJLvmWj+PxxNj6Mw1b6X0uK9eq1VRuW1y1gHK+7T92GxakyreJW1rIC1DfdVxJZXEv+mN17GSSekdUG/FGadjIr4lUwInPr10g2inmICwM+1sEDMiNBC0/e0mGoAdIe+RHngLTdJShxC7EedfNlIianBGykul3zXGiVr51wxHeI3IqD3tRTs6J9+Fyu6XPtH1+MN/rquVJgpposoPMljRDIWDB/elORmtL47ZEzOcHEPe8KJ7Ha4Y+YBiwo751UIptwgy9OHpU87MpJx9tjSmEr/apVdJ7 arunpoonia@Aruns-MacBook-Pro.local"

services:
  - name: exfo-worx
    type: public
    port: 8080
    protocols:
      - tcp
    destination:
      port: 8080
      address: 10.0.0.8
  - name: rdp-hqpc1
    type: public
    port: 33899
    protocols:
      - tcp
    destination:
      port: 3389
      address: 10.0.0.190
  - name: rdp-branch1pc1
    type: public
    port: 33891
    protocols:
      - tcp
    destination:
      port: 3389
      address: 10.0.0.110


###################
#                 #
# N E T W O R K S #
#                 #
###################
networks:
  # - name: private
  #   cidr: 10.0.0.0/24
  #   dns:
  #   - 10.0.0.1
  #   dhcp: true
  # HQ networks
  - name: HQ-Int
    cidr: 10.10.90.0/24
    dns: 10.0.0.1
    dhcp: true
  - name: HQ-Sub1
    cidr: 192.168.90.0/24
    dns: 10.0.0.1
    dhcp: false

  # Branch1 networks
  - name: BR1-Int
    cidr: 10.10.10.0/24
    dns: 10.0.0.1
    dhcp: true
  - name: BR1-Sub1
    cidr: 192.168.10.0/24
    dns: 10.0.0.1
    dhcp: false
  - name: BR1-EMS
    cidr: 192.168.20.0/24
    dns: 10.0.0.1
    dhcp: false
  - name: BR1-Test
    cidr: 192.168.30.0/24
    dns: 10.0.0.1
    dhcp: false


  # dummy networks
  # used to isolate second uplink of NSGVs
  - name: dummy-wan
    cidr: 255.255.255.0/24
    dhcp: false


#################
#               #
# S E R V E R S #
#               #
#################
servers:
  # - name: vsd01
  #   image: vsd01_NUX_5.3.3U3_VNS
  #   flavor: nux.vsd
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.2
  # - name: vsc01
  #   image: vsc01_NUX_5.3.3U3_VNS
  #   flavor: ceph.vsc
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.3
  # - name: elastic
  #   image: elastic_NUX_5.3.3U3_VNS
  #   flavor: nux.vsd
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.5
  # - name: utility
  #   image: utility_NUX_5.3.3U3_VNS
  #   flavor: m1.small
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.33

  # VSCs
  - name: vsc-i
    image: vsc_nux_base-vns-single-underlay-5.4.1
    flavor: ceph.vsc
    interfaces:
      - index: 0
        network: private
        address: 10.0.0.10
      - index: 1
        network: HQ-Int
        address: 10.10.90.20

  # Routers
  - name: PE-Internet
    flavor: m1.small
    image: CentOS-7.5-x86_64-GenericCloud
    interfaces:
      - network: private
        address: 10.0.0.210
        index: 0
      - network: HQ-Int
        address: 10.10.90.1
        index: 1
      - network: BR1-Int
        address: 10.10.10.1
        index: 2

  # Exfo VM 
  - name: exfo-worx
    image: nux_exfo_worx_10.1_sp6
    flavor: m1.large
    interfaces:
      - index: 0
        network: private
        address: 10.0.0.8

  # HQ servers
  - name: HQ-nsg1
    flavor: m1.medium
    image: nux_nsg_5.4.1
    interfaces:
      - network: HQ-Int
        address: 10.10.90.10
        index: 0
      - network: dummy-wan
        address: 255.255.255.1
        index: 1
      - network: HQ-Sub1
        address: 192.168.90.1
        index: 2
        
  - name: HQ-pc1
    image: nux_branch_pc
    flavor: m1.small
    interfaces:
      - index: 0
        network: private
        address: 10.0.0.190
      - index: 1
        network: HQ-Sub1
        address: 192.168.90.2

  # Branch1 servers
  - name: Branch1-nsg1
    flavor: m1.medium
    image: nux_nsg_5.4.1
    interfaces:
      - network: BR1-Int
        address: 10.10.10.10
        index: 0
      - network: dummy-wan
        address: 255.255.255.2
        index: 1
      - network: BR1-EMS  # for EMS PC
        address: 192.168.20.1
        index: 2
      - network: BR1-Test  # for Win10 VIAVI Test PC
        address: 192.168.30.1
        index: 3
      - network: BR1-Sub1  # installer pc, thus the last port
        address: 192.168.10.1
        index: 4

  - name: Branch1-pc1
    image: nux_branch_pc
    flavor: m1.small
    interfaces:
      - index: 0
        network: private
        address: 10.0.0.110
      - index: 1
        network: BR1-Sub1
        address: 192.168.10.2


  - name: ems1-pc1
    image: nux_branch_pc
    flavor: m1.small
    interfaces:
      - index: 0
        network: private
        address: 10.0.0.120
      - index: 1
        network: BR1-EMS
        address: 192.168.20.2

  - name: Branch1-TestPC
    image: nux_win10pro
    flavor: m2.medium
    interfaces:
      - index: 0
        network: BR1-Test
        address: 192.168.30.2



