# nuxctl (nuxctl.nuagex.io) template
# compatible with nuxctl 0.6.0+ version
template: 5982662519b6fd00018f9981
name: viavi-1-underlay-lab2
sshKeys:
  - name: demo
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0jLLF2c7sSUHCwFJ1cpj0mTNRfemi6XMKxAf7H4gIzs/joL18W+wlSrnHnu801bDLc2RNg8dvOvXmzjzZrKKMInWMXrzb0zjljCPumYWlI/koWAIMzpENjeRjWrB22WFVOVDW4GkphzhchFWFPSF9xxU4i3MPHn3HYZiy6ieLOvknplQDivTXcLwRjvenK35gjLPxo4nFhQWyUdzPLLCb/NUx/CGjkh10qwVfw+AWw3x3boqxwBXitPjLJ+ocfZVohAWupKuvsTNzlh8m39imI5pi9qTFT1x9YtkYsTYCy2iz2HCirqy+8BC/CPCyHuEjs8ZT9OFHHQtjB/qgzfTp"

services:
  - name: rdp-hqpc1
    type: public
    port: 33899
    protocols:
      - tcp
    destination:
      port: 3389
      address: 10.0.0.199
  - name: rdp-branch1pc1
    type: public
    port: 33891
    protocols:
      - tcp
    destination:
      port: 3389
      address: 10.0.0.101
  - name: amqp
    type: public
    port: 5672
    protocols:
      - tcp
    destination:
      port: 5672
      address: 10.0.0.2
  - name: stomp
    type: public
    port: 61614
    protocols:
      - tcp
    destination:
      port: 61614
      address: 10.0.0.2

###################
#                 #
# N E T W O R K S #
#                 #
###################
networks:
  # - name: private
  #   cidr: 10.0.0.0/24
  #   dns:
  #   - 10.0.0.1
  #   dhcp: true
  # HQ networks
  - name: HQ-Internet
    cidr: 10.10.99.0/24
    dns: 10.0.0.1
    dhcp: true
  - name: HQ-Sub1
    cidr: 10.30.99.0/24
    dns: 10.0.0.1
    dhcp: false

  # Branch1 networks
  - name: Branch1-Internet
    cidr: 10.10.1.0/24
    dns: 10.0.0.1
    dhcp: true
  - name: Branch1-Sub1
    cidr: 10.30.1.0/24
    dns: 10.0.0.1
    dhcp: false
  - name: Branch1-EMS_Sub
    cidr: 10.31.1.0/24
    dns: 10.0.0.1
    dhcp: false
  - name: Branch1-Test_Sub
    cidr: 10.32.1.0/24
    dns: 10.0.0.1
    dhcp: false

  # dummy networks
  # used to isolate wan interfaces of NSGVs
  - name: dummy-wan
    cidr: 255.255.255.0/28
    dhcp: false


#################
#               #
# S E R V E R S #
#               #
#################
servers:
  # - name: vsd01
  #   image: vsd01_NUX-VNS-5.3.2
  #   flavor: nux.vsd
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.2
  # - name: vsc01
  #   image: vsc01_NUX-VNS-5.3.2
  #   flavor: ceph.vsc
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.3
  # - name: portal
  #   image: portal_NUX-VNS-5.3.2
  #   flavor: ceph.vsd
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.4
  # - name: elastic
  #   image: elastic_NUX-VNS-5.3.2
  #   flavor: nux.vsd
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.5
  # - name: catsvm
  #   image: catsvm_NUX_5.2.2_PORTAL
  #   flavor: m2.small
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.7
  # - name: utility
  #   image: utility_NUX-VNS-5.3.2
  #   flavor: m1.small
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.33

  # VSCs
  - name: vsc-i
    image: nux_vsc_5.3.2
    flavor: ceph.vsc
    interfaces:
      - index: 0
        network: private
        address: 10.0.0.10
      - index: 1
        network: HQ-Internet
        address: 10.10.99.10

  # HQ servers
  - name: HQ-nsg1
    flavor: m1.medium
    image: nux_nsg_5.3.2u1
    interfaces:
      - network: HQ-Internet
        address: 10.10.99.99
        index: 0
      - network: dummy-wan
        address: 255.255.255.4
        index: 1
      - network: HQ-Sub1
        address: 10.30.99.99
        index: 2
  - name: HQ-pc1
    image: nux_branch_pc
    flavor: m1.small
    interfaces:
      - index: 0
        network: private
        address: 10.0.0.199
      - index: 1
        network: HQ-Sub1
        address: 10.30.99.113

  # Branch1 servers
  - name: Branch1-nsg1
    flavor: m1.medium
    image: nux_nsg_5.3.2u1
    interfaces:
      - network: Branch1-Internet
        address: 10.10.1.11
        index: 0
      - network: dummy-wan
        address: 255.255.255.1
        index: 1
      - network: Branch1-EMS_Sub  # for EMS PC
        address: 10.31.1.11
        index: 2
      - network: Branch1-Test_Sub  # for Win10 VIAVI Test PC
        address: 10.32.1.11
        index: 3
      - network: Branch1-Sub1  # installer pc, thus the last port
        address: 10.30.1.11
        index: 4
  - name: Branch1-pc1
    image: nux_branch_pc
    flavor: m1.small
    interfaces:
      - index: 0
        network: private
        address: 10.0.0.101
      - index: 1
        network: Branch1-Sub1
        address: 10.30.1.101
  - name: ems1-pc1
    image: nux_branch_pc
    flavor: m1.small
    interfaces:
      - index: 0
        network: private
        address: 10.0.0.198
      - index: 1
        network: Branch1-EMS_Sub
        address: 10.31.1.101
  - name: Branch1-TestPC
    image: nux_win10pro
    flavor: m2.medium
    interfaces:
      - index: 0
        network: Branch1-Test_Sub
        address: 10.32.1.103


  # Routers
  - name: PE-Internet
    flavor: m1.small
    image: CentOS-7.5-x86_64-GenericCloud
    interfaces:
      - network: private
        address: 10.0.0.210
        index: 0
      - network: HQ-Internet
        address: 10.10.99.1
        index: 1
      - network: Branch1-Internet
        address: 10.10.1.1
        index: 2
