template: 5c35217192f86a000180be8f
name: 0010-vns-basic-1
sshKeys:
  - name: demo
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0jLLF2c7sSUHCwFJ1cpj0mTNRfemi6XMKxAf7H4gIzs/joL18W+wlSrnHnu801bDLc2RNg8dvOvXmzjzZrKKMInWMXrzb0zjljCPumYWlI/koWAIMzpENjeRjWrB22WFVOVDW4GkphzhchFWFPSF9xxU4i3MPHn3HYZiy6ieLOvknplQDivTXcLwRjvenK35gjLPxo4nFhQWyUdzPLLCb/NUx/CGjkh10qwVfw+AWw3x3boqxwBXitPjLJ+ocfZVohAWupKuvsTNzlh8m39imI5pi9qTFT1x9YtkYsTYCy2iz2HCirqy+8BC/CPCyHuEjs8ZT9OFHHQtjB/qgzfTp"

###################
#                 #
# S E R V I C E S #
#                 #
###################
services:
  # - name: vsd
  #   type: public
  #   port: 8443
  #   urlScheme: https
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 18443
  #     address: 10.0.0.2
  # - name: vsc-openflow
  #   type: public
  #   port: 6633
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 6633
  #     address: 10.0.0.3
  # - name: vsc-jsonrpc
  #   type: public
  #   port: 7406
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 7406
  #     address: 10.0.0.3
  # - name: vsc-dtls-vxlan
  #   type: public
  #   port: 4789
  #   protocols:
  #   - udp
  #   destination:
  #     port: 4789
  #     address: 10.0.0.3
  # - name: vsc-dtls-ipsec
  #   type: public
  #   port: 4500
  #   protocols:
  #   - udp
  #   destination:
  #     port: 4500
  #     address: 10.0.0.3
  # - name: vsc-ntp
  #   type: public
  #   port: 123
  #   protocols:
  #   - udp
  #   destination:
  #     port: 123
  #     address: 10.0.0.3
  # - name: proxy-statistics
  #   type: public
  #   port: 39090
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 39090
  #     address: 10.0.0.33
  # - name: vsc-jsonrpc-nsg
  #   type: public
  #   port: 7407
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 7407
  #     address: 10.0.0.3
  # - name: proxy-prebootstrap
  #   type: public
  #   port: 12443
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 12443
  #     address: 10.0.0.33
  # - name: proxy-postbootstrap
  #   type: public
  #   port: 11443
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 11443
  #     address: 10.0.0.33
  # - name: vsc-bgp-tls
  #   type: public
  #   port: 48179
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 48179
  #     address: 10.0.0.3
  # - name: proxy-upgrade-repository
  #   type: public
  #   port: 80
  #   urlScheme: http
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 80
  #     address: 10.0.0.33
  # - name: elasticsearch-api
  #   type: public
  #   port: 6200
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 6200
  #     address: 10.0.0.5
  - name: rdp-branch1pc1
    type: public
    port: 33891
    protocols:
      - tcp
    destination:
      port: 3389
      address: 10.0.0.101
  - name: rdp-branch2pc1
    type: public
    port: 33892
    protocols:
      - tcp
    destination:
      port: 3389
      address: 10.0.0.102
  - name: amqp
    type: public
    port: 5672
    protocols:
      - tcp
    destination:
      port: 5672
      address: 10.0.0.2

###################
#                 #
# N E T W O R K S #
#                 #
###################
networks:
  # - name: private
  #   cidr: 10.0.0.0/24
  #   dns:
  #   - 10.0.0.1
  #   dhcp: true
  - name: dummy1
    cidr: "255.255.255.0/24"
    dns:
    dhcp: false

  - name: nsg1-lan
    cidr: "172.17.1.0/24"
    dns: "10.0.0.1"
    dhcp: false

  - name: nsg2-lan
    cidr: "172.17.2.0/24"
    dns: "10.0.0.1"
    dhcp: false

###################
#                 #
#  S E R V E R S  #
#                 #
###################
servers:
  # - name: vsd01
  #   image: vsd01_NUX_5.3.3U3_VNS
  #   flavor: nux.vsd
  #   interfaces:
  #     - index: 0
  #       network: private
  #       address: 10.0.0.2
  # - name: vsc01
  #   image: vsc01_NUX_5.3.3U3_VNS
  #   flavor: ceph.vsc
  #   interfaces:
  #     - index: 0
  #       network: private
  #       address: 10.0.0.3
  # - name: elastic
  #   image: elastic_NUX_5.3.3U3_VNS
  #   flavor: nux.vsd
  #   interfaces:
  #     - index: 0
  #       network: private
  #       address: 10.0.0.5
  # - name: utility
  #   image: utility_NUX_5.3.3U3_VNS
  #   flavor: m1.small
  #   interfaces:
  #     - index: 0
  #       network: private
  #       address: 10.0.0.33
  - name: nsg1
    flavor: "m1.small"
    image: "nux_nsg_5.3.3U1"
    interfaces:
      - network: private
        address: "10.0.0.11"
        index: 0
      - network: dummy1
        address: "255.255.255.1"
        index: 1
      - network: nsg1-lan
        address: "172.17.1.1"
        index: 2
  - name: pc1
    image: "nux_branch_pc"
    flavor: "m1.small"
    interfaces:
      - index: 0
        network: private
        address: "10.0.0.101"
      - index: 1
        network: nsg1-lan
        address: "172.17.1.101"

  - name: nsg2
    flavor: "m1.small"
    image: "nux_nsg_5.3.3U1"
    interfaces:
      - network: private
        address: "10.0.0.12"
        index: 0
      - network: dummy1
        address: "255.255.255.2"
        index: 1
      - network: nsg2-lan
        address: "172.17.2.1"
        index: 2
  - name: pc2
    image: "nux_branch_pc"
    flavor: "m1.small"
    interfaces:
      - index: 0
        network: private
        address: "10.0.0.102"
      - index: 1
        network: nsg2-lan
        address: "172.17.2.102"
